Repository sighupio/fury-kubernetes-ingress, pull requests merged in 2020-04, with the labels that each got.

#22 Update ingress-nginx to 0.30.0
  README.md
  katalog/dual-nginx/README.md
  katalog/nginx/README.md
  katalog/nginx/bases/controller/deployment.yml
  katalog/nginx/bases/controller/kustomization.yaml
Labels: enhancement

#21 Update Forecastle to v1.0.42
  katalog/forecastle/README.md
  katalog/forecastle/config.yaml
  katalog/forecastle/deploy.yml
  katalog/forecastle/kustomization.yaml
  katalog/forecastle/rbac.yml
Labels: enhancement

#23 Update cert-manager (pre-release v1.6.0)
  README.md
  docs/releases/v1.6.0.md
  katalog/cert-manager/README.md
  katalog/cert-manager/cainjector/deploy.yml
  katalog/cert-manager/cainjector/rbac.yml
  katalog/cert-manager/cert-manager-controller/crd.yml
  katalog/cert-manager/cert-manager-controller/deploy.yml
  katalog/cert-manager/cert-manager-controller/issuer.yml
  katalog/cert-manager/cert-manager-controller/ns.yml
  katalog/cert-manager/cert-manager-controller/rbac.yml
  katalog/cert-manager/kustomization.yaml
  katalog/cert-manager/webhook/apiservice.yml
  katalog/cert-manager/webhook/deploy.yml
  katalog/cert-manager/webhook/kustomization.yaml
  katalog/cert-manager/webhook/tls.yml
  katalog/cert-manager/webhook/webhookvalidatingconfig.yml
  katalog/tests/tests.bats
Labels: help wanted

#24 Enable access log
  .bumpversion.cfg
  README.md
  docs/releases/v1.6.1.md
  examples/nginx-config/Furyfile.yml
  examples/nginx-default-ssl-certificate/Furyfile.yml
  examples/nginx-ldap-auth/Furyfile.yml
  katalog/nginx/bases/controller/cm.yml
Labels: bug, enhancement
